### PR TITLE
Add disk usage card to homescreen.

### PR DESCRIPTION
**Pull request by miketweaver**
I have 2 things I don't like about this pull request, but I'll put it here anyways.

First, you have to run this upon initial setup:
chmod +x /opt/piratebox/www/cgi-bin/diskwrite.py
I couldn't find where you chmod the cgi-bin's files and why mine wasn't getting execute perms. I'll look into it. 

Second, /opt/piratebox/share/Shared/ is hardcoded into diskwrite.py and diskusage.py.

Other than that, I think it works great. Let me know your thoughts.

### CODE REVIEW

**Comment by miketweaver** [comment]
This should add a card like this:

image

**Comment by miketweaver** [comment]
Also, I just sort of added the configuration settings in random places. I wasn't quite sure where to put them to make it "flow".

**Comment by MaStr** [comment]
I did a quick review and it looks good. It full-fills the idea of not generating workload intensive stuff on each pageload. 

Would solve #53 

The only thing, I'm thinking about, is where to push it too. (Create a release branch, or bring it to the development branch).

**Comment by MaStr** [comment]
Ok, I tested it today. It works on OpenWrt like you put it into the PR.

A few additional comments/modifications, I like to have:

1. Change the meta-tag to content="disk usage" 
2. Do you think you can implement a check, that the rewrite of the usage stats is only triggered, when the generated file is older then 5 minutes ?  That would reduce the load on the USB stick significantly, if somebody starts to hammer on the reload button. If sombody does that, it slows down the box significantly
3. Please add your name to the AUTHOR file

I'll put your change into a 1.1 release and I'll see what I can add there as well (like installing & enabling PHP  or something).

Thank you very much.

**Comment by miketweaver** [comment]
Added the last modified check, meta-tag change, and added to the authors file. Let me know how it works out on OpenWRT. I don't have one of those devices for testing.

**Comment by miketweaver** [comment]
made a few bugfixes.

**Comment by MaStr** [comment]
Thank you alot for that. 
I'll test it this afternoon/evening.

**Comment by MaStr** [comment]
Like discussed in the IRC

```
Traceback (most recent call last):
  File "/opt/piratebox/www/cgi-bin/diskwrite.py", line 12, in <module>
    get_usage("/opt/piratebox/share/Shared/")
  File "/opt/piratebox/python_lib/diskusage.py", line 46, in get_usage
    file_mod_time = modification_date(htmlfilename)
  File "/opt/piratebox/python_lib/diskusage.py", line 25, in modification_date
    moddate = os.path.getmtime(filename)
  File "/usr/local/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/opt/piratebox/www/diskusage.html'
```

**Comment by MaStr** [comment]
Please add a tooltip (mouseover) at the refresh button that contains something like "The refresh of the status bar is updated every 5 minutes".
Well that is actually not true..... but so, it seems it does not work while uploading.

Or, lock the refresh button for 2 minutes

**Comment by miketweaver** [comment]
Ok. This try-catch will re-create the diskusage.html file even if it has been deleted. I've tested it and it works well.

(Note, if you delete the chat_content.html file it will have the same problem my disk usage had. You might want to fix that as well)

**Comment by miketweaver** [comment]
I have added the tooltips and the Button Text change while the ajax is loading. Let me know how your testing goes.

**Comment by MaStr** [comment]
Hi,
ok that looks quite good! 
The only very last thing is, that the mouse-over box doesn't disapear after clicking and leaving the button.

Testing now on my mobile devices....

Many many thanks
best regards Matthias

**Comment by miketweaver** [comment]
The mouse-over box issue is related to having an old version of jquery. You can update it, but I'm not sure what ramifications it would have on the other parts of the page.

http://code.jquery.com/jquery-2.1.4.min.js

**Comment by deavmi** [comment]
Aweosme :+1:

**Comment by MaStr** [comment]
Merged to feature branch 1.1.0

**Pull request closed without merging**
