### PR TITLE
Lock Shoutbox

### PR DESCRIPTION
**Pull request by miketweaver**
This should 'lock' the sending button until the post is finished.

Should solve #67 .

### CODE REVIEW

**Comment by MaStr** [comment]
The button seems not to be disabled, it seems not to work.

In addition, I have to admit, that you have fixed the problem of the slow loading shoutbox when posting :+1:

**Comment by miketweaver** [comment]
I'm not sure I understand what you're saying. Are you saying that the button does not disable? Or that I fixed the problem?

In most cases, the button should only be disabled for milliseconds. If the system is preforming fast, you shouldn't even see it at all. 

Yes, you can send empty lines. This is the way it's always functioned. I only added an event before and after the POST to `"/cgi-bin/psowrte.py"`. I didn't change the POST itself.

**Comment by miketweaver** [comment]
I noticed that the button text didn't switch at the right time. That should be fixed now.

**Comment by MaStr** [comment]
that looks very good. 
I'm testing it on my mobile devices, but I guess that should work out as well.

**Comment by MaStr** [comment]
merged to feature branch 1.1.0

**Pull request closed without merging**
